export const storeProducts = [
  {
    id: 1,
    title: "our newst plant",
    img: "img/plant1.jpeg",
    price: 10,
    company: "Dew point",
    info: "",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "",
    img: "img/plant2.jpeg",
    price: 20,
    company: "dew point",
    info: "",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "",
    img: "img/plant3.jpeg",
    price: 18,
    company: "dew point",
    info: "",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "",
    img: "img/plant4.jpeg",
    price: 20,
    company: "dew point",
    info: "",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "",
    img: "img/plant5.jpeg",
    price: 15,
    company: "",
    info: "",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "",
    img: "img/plant6.jpeg",
    price: 20,
    company: "",
    info: "",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "",
    img: "img/plant7.jpeg",
    price: 20,
    company: "",
    info: "",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "",
    img: "img/plant8.jpeg",
    price: 30,
    company: "dew point",
    info: "",
    inCart: false,
    count: 0,
    total: 0,
  },

  {
    id: 9,
    title: "",
    img: "img/plant9.jpeg",
    price: 15,
    company: "dew point",
    info: "",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "",
    img: "img/plant10.jpeg",
    price: 30,
    company: "",
    info: "",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: "",
    img: "img/plant11.jpeg",
    price: 15.99,
    company: "",
    info: "",
    inCart: false,
    count: 0,
    total: 0,
  },

  {
    id: 12,
    title: "",
    img: "img/plant12.jpeg",
    price: 20,
    company: "dew point",
    info: "",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "liberian",
  // img: "img/produt-11.jpg",
  price: 10,
  company: "",
  info:
    "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
  inCart: false,
  count: 0,
  total: 0,
};
